articles = [
    {'id': 0, 'url': 'test', 'organization': 'lvz', 'author_array': ["Mark Daniel"],
     'author_is_abbreviation': [False], 'author_namespace_array': ["Borna"], 'published_at': '2010-01-01T00:00:00+00:00'},
    {'id': 1, 'url': 'test', 'organization': 'lvz', 'author_array': ["Mark Daniel", "Hannah Suppa"],
     'author_is_abbreviation': [False, False], 'author_namespace_array': ["Borna"], 'published_at': '2010-02-01T00:00:00+00:00'},
    {'id': 2, 'url': 'test', 'organization': 'lvz', 'author_array': ["Theresa Moosmann", "md"],
     'author_is_abbreviation': [False, True], 'author_namespace_array': ["Leipzig"], 'published_at': '2010-03-01T00:00:00+00:00'},
    {'id': 3, 'url': 'test', 'organization': 'lvz', 'author_array': ["tm", "has"],
     'author_is_abbreviation': [True, True], 'author_namespace_array': ["Leipzig", "Borna"], 'published_at': '2010-04-01T00:00:00+00:00'},
    {'id': 4, 'url': 'test', 'organization': 'lvz', 'author_array': ["mad", "lvz"],
     'author_is_abbreviation': [True, True], 'author_namespace_array': ["Sport"], 'published_at': '2010-04-05T00:00:00+00:00'},
    {'id': 5, 'url': 'test', 'organization': 'lvz', 'author_array': ["md", "tm"],
     'author_is_abbreviation': [True, True], 'author_namespace_array': ["Borna"], 'published_at': '2010-04-10T00:00:00+00:00'},
    {'id': 6, 'url': 'test', 'organization': 'lvz', 'author_array': ["Tilmann Prüfer"],
     'author_is_abbreviation': [False], 'author_namespace_array': ["Leipzig"], 'published_at': '2010-04-20T00:00:00+00:00'},
    {'id': 7, 'url': 'test', 'organization': 'lvz', 'author_array': ["Tim Meyer"],
     'author_is_abbreviation': [False], 'author_namespace_array': ["Borna"], 'published_at': '2010-04-30T00:00:00+00:00'},
    {'id': 8, 'url': 'test', 'organization': 'lvz', 'author_array': ["Theresa Moosmann"],
     'author_is_abbreviation': [False], 'author_namespace_array': ["Leipzig"], 'published_at': '2010-05-01T00:00:00+00:00'},
    {'id': 9, 'url': 'test', 'organization': 'lvz', 'author_array': ["lvz"],
     'author_is_abbreviation': [True], 'author_namespace_array': ["Sport"], 'published_at': '2010-05-10T00:00:00+00:00'},
    {'id': 10, 'url': 'test', 'organization': 'lvz', 'author_array': ["Jan Armin-Döbeln"],
     'author_is_abbreviation': [False], 'author_namespace_array': ["Sport"], 'published_at': '2010-05-10T00:00:00+00:00'},
    {'id': 11, 'url': 'test', 'organization': 'lvz', 'author_array': ["jad"],
     'author_is_abbreviation': [True], 'author_namespace_array': ["Sport"], 'published_at': '2010-05-10T00:00:00+00:00'},
    {'id': 12, 'url': 'test', 'organization': 'lvz', 'author_array': ["qxy"],
     'author_is_abbreviation': [True], 'author_namespace_array': ["Sport"], 'published_at': '2010-05-10T00:00:00+00:00'},
]